Models/ViewModel/ReleasedViewModel.cs
using IIMSv1.Models.Shared;

namespace IIMSv1.Models.ViewModel
{
    public class ReleasedViewModel
    {
        public List<_ItemReleasedModel> items { get; set; } = new List<_ItemReleasedModel>();
        public List<Released> releasedItems { get; set; } = new List<Released>();
        public List<Department> departments { get; set; } = new List<Department>();
        public List<string> Months { get; set; } = new List<string>();
        public PaginationModel PaginationModel { get; set; }
        public int year { get; set; }
        public string DeptId { get; set; } = string.Empty;
        public string DeptTxt { get; set; } = string.Empty;
        public string perPage { get; set; } = string.Empty;
        public string searchtxt { get; set; } = string.Empty;
        public string YearFrom { get; set; } = string.Empty;
        public string YearTo { get; set;} = string.Empty;
        public string TotalCount { get; set; } = string.Empty;
        public string toReceiveCount { get; set; } = string.Empty;
        public string pullOutCount { get; set; } = string.Empty;
        public string receivedCount { get; set; } = string.Empty;
        public string year1Text { get; set; } = string.Empty;
        public string year2Text { get; set; } = string.Empty; 
        public string deptText { get; set; } = string.Empty;
    }
}

Controllers/PrintReleasedController.cs
using IIMSv1.Data;
using IIMSv1.Models;
using IIMSv1.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IIMSv1.Controllers
{
    public class PrintReleasedController : Controller
    {
        private readonly InventoryDbContext _context;
        private readonly UserManager<AccountUser> _userManager;
        private readonly SignInManager<AccountUser> _signInManager;

        public PrintReleasedController(InventoryDbContext context, UserManager<AccountUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<AccountUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> Index(string department = "", string relnum = "", string year1 = "", string year2 = "", string searchtxt = "")
        {   
            string[] arrMonth = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
            DateOnly? YearStart = null;
            DateOnly? YearEnd = null;
            if (year1 != "" || year2 != "")
            {
                var Year1 = year1 + "-01-01";

                var needYear = year2 + "-12";
                DateTime year = Convert.ToDateTime(needYear);
                var ConvertYear = DateTime.DaysInMonth(year.Year, year.Month);
                var Year2 = needYear + "-" + ConvertYear;

                DateTime YearFrom = Convert.ToDateTime(Year1);
                DateOnly start = DateOnly.FromDateTime(YearFrom);
                YearStart = start;

                DateTime YearTo = Convert.ToDateTime(Year2);
                DateOnly end = DateOnly.FromDateTime(YearTo);
                YearEnd = end;
            }

            IQueryable<Released> released = _context.Released
                .Include(x => x.Department)
                .Include(x => x.item)
               .Where(x => x.DepartmentId.Contains(department) && x.Department.IsActive.Equals(true));

            List<Released> rels = new List<Released>();
            if (YearStart != null && YearEnd != null)
            {
                List<Released> release = released
                    .Where(x => x.DateReleased >= YearStart && x.DateReleased <= YearEnd)
                    .ToList();

                foreach (var rel in release)
                {
                    rels.Add(rel);
                }
            }
            else
            {
                List<Released> release = released
                    .ToList();

                foreach (var rel in release)
                {
                    rels.Add(rel);
                }
            }
            IQueryable<Items> QueryItem = _context.Items
                .Where(x => x.ItemName.Contains(searchtxt));

            int CountTotal = 0;
            int CountToReceive = 0;
            int CountReceived = 0;
            int CountPullout = 0;
            List<int> years = new List<int>();
            List<Department> depts = new List<Department>();
            foreach (var rel in rels)
            {
                bool isToReceive = rel.Received.Equals(false) && rel.Pullout.Equals(false) && QueryItem.Any(x => x.Id.Equals(rel.ItemId));
                if (isToReceive)
                {
                    CountToReceive += rel.ReleaseQuantity;
                }
                bool isReceived = rel.Received.Equals(true) && rel.Pullout.Equals(false) && QueryItem.Any(x => x.Id.Equals(rel.ItemId));
                if (isReceived)
                {
                    CountReceived += rel.ReleaseQuantity;
                }
                bool isPullout = rel.Received.Equals(false) && rel.Pullout.Equals(true) && QueryItem.Any(x => x.Id.Equals(rel.ItemId));
                if (isPullout)
                {
                    CountPullout += rel.ReleaseQuantity;
                }

                bool isYearExists = years.Any(x => x.Equals(rel.DateReleased.Year) && QueryItem.Any(x => x.Id.Equals(rel.ItemId)));
                if (!isYearExists)
                {
                    years.Add(rel.DateReleased.Year);
                }
                bool isTotal = QueryItem.Any(x => x.Id.Equals(rel.ItemId));
                if (isTotal)
                {
                    CountTotal += rel.ReleaseQuantity;
                }
                bool isDepartmentExists = depts.Any(x => x.Id.Equals(rel.DepartmentId));
                if (!isDepartmentExists)
                {
                    depts.Add(rel.Department);
                }
            }
            List<Items> items = QueryItem
                .OrderBy(x => x.ItemName)
                .Where(x => x.IsEnabled.Equals(true) && x.itemQuantity != null)
                .ToList();

            List<Department> departments = depts
                .OrderBy(x => x.NormalizedName)
                .Where(x => x.IsActive.Equals(true))
                .ToList();

            PrintReleasedViewModel model = new PrintReleasedViewModel();
            if(year1 != "" && year2 != "")
            {
                model.year1Text = year1;
                model.year2Text = year2;
            }
            else
            {
                model.year1Text = years.Min().ToString();
                model.year2Text = years.Max().ToString();

            }
            model.departments = departments;
            model.Released = rels;
            model.relnumText = relnum;
            model.Months = arrMonth.ToList();
            model.items = items;
            model.toReceiveCount = CountToReceive.ToString();
            model.receivedCount = CountReceived.ToString();
            model.pullOutCount = CountPullout.ToString();
            model.TotalCount = CountTotal.ToString();

            return View(model);
        }
    }
}

Controllers/ReleasedController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IIMSv1.Data;
using IIMSv1.Models;
using IIMSv1.Models.Shared;
using IIMSv1.Models.ViewModel;

namespace IIMSv1.Controllers
{
    public class ReleasedController : Controller
    {
        private readonly InventoryDbContext _context;
        private readonly UserManager<AccountUser> _userManager;
        private readonly SignInManager<AccountUser> _signInManager;

        public ReleasedController(InventoryDbContext context, UserManager<AccountUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<AccountUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        //Filter 
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> Filter(string dept,string search, int page, string yearFrom, string yearTo, int entries)
        {
            return RedirectToAction("Index", "Released", new { page = page,search = search, dept = dept, yearFrom = yearFrom, yearTo = yearTo, entries = entries });
        }

        //Index
        [HttpGet]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> Index(string dept = "", string search = "", int page = 1, string yearFrom = "", string yearTo = "", int entries = 10)
        {

            string deptId = dept.Trim().ToString();
            string searchTxt = search.Trim().ToString();
            string yearFromTxt = yearFrom.Trim().ToString();
            string yearToTxt = yearTo.Trim().ToString();

            DateOnly? YearStart = null;
            DateOnly? YearEnd = null;
            if (yearFrom != "" || yearTo != "")
            {
                var Year1 = yearFrom + "-01-01";

                var needYear = yearTo + "-12";
                DateTime year = Convert.ToDateTime(needYear);
                var ConvertYear = DateTime.DaysInMonth(year.Year, year.Month);
                var Year2 = needYear + "-" + ConvertYear;

                DateTime YearFrom = Convert.ToDateTime(Year1);
                DateOnly start = DateOnly.FromDateTime(YearFrom);
                YearStart = start;

                DateTime YearTo = Convert.ToDateTime(Year2);
                DateOnly end = DateOnly.FromDateTime(YearTo);
                YearEnd = end;
            }
            

            IQueryable<Released> deptReleased = _context.Released
                .Include(x => x.item)
                .ThenInclude(x => x.itemType)
                .Include(x => x.Department)
                .Where(x => x.DepartmentId.Contains(deptId) && x.Department.IsActive.Equals(true));

            List<Released> released = new List<Released>();
            if (YearStart != null && YearEnd != null)
            {
                List<Released> releases = deptReleased
                    .Where(x => x.DateReleased >= YearStart
                    && x.DateReleased <= YearEnd)
                    .ToList();
                foreach (var rel in releases)
                {
                    released.Add(rel);
                }
            }
            else
            {
                List<Released> releases = deptReleased
                .ToList();
                foreach(var rel in releases)
                {
                    released.Add(rel);
                }

            }
            List<Items> item = _context.Items
                .Include(x => x.itemType)
                .OrderBy(x => x.itemType.itemType)
                .Where(x => x.IsEnabled.Equals(true) && x.itemQuantity != null
                 && x.itemType.itemType.Contains(searchTxt))
                .ToList();

            List<_ItemReleasedModel> items1 = new List<_ItemReleasedModel>();
            int index = 0;
            foreach(var i in item)
            {
                index += 1;
                _ItemReleasedModel newitem = new _ItemReleasedModel()
                {
                    num = index,
                    Id = i.Id,
                    Name = i.ItemName,
                };
                items1.Add(newitem);
            }
            int CountTotal = 0;
            int CountToReceive = 0;
            int CountReceived = 0;
            int CountPullout = 0;
            List<int> years = new List<int>();
            foreach (var rel in released)
            {
                bool isToReceive = rel.Received.Equals(false) && rel.Pullout.Equals(false) && items1.Any(x => x.Id.Equals(rel.ItemId));
                if (isToReceive)
                {
                    CountToReceive += rel.ReleaseQuantity;
                }
                bool isReceived = rel.Received.Equals(true) && rel.Pullout.Equals(false) && items1.Any(x => x.Id.Equals(rel.ItemId));
                if (isReceived)
                {
                    CountReceived += rel.ReleaseQuantity;
                }
                bool isPullout = rel.Received.Equals(false) && rel.Pullout.Equals(true) && items1.Any(x => x.Id.Equals(rel.ItemId));
                if (isPullout)
                {
                    CountPullout += rel.ReleaseQuantity;
                }
                bool isTotal =  items1.Any(x => x.Id.Equals(rel.ItemId));
                if (isTotal)
                {
                    CountTotal += rel.ReleaseQuantity;
                }

                bool isYearExists = years.Any(x => x.Equals(rel.DateReleased.Year) && items1.Any(x => x.Id.Equals(rel.ItemId)));
                if (!isYearExists)
                {
                    years.Add(rel.DateReleased.Year);
                }
            }

            int recordsperpage = entries;
            int recordtotal = items1.Count();
            int pagetotal = Global.GetPaginationTotalPages(recordtotal, recordsperpage);

            if (page < 1 || (page > pagetotal && recordtotal > 0))
            {
                page = 1;
            }

            List<_ItemReleasedModel> items = items1
                .Skip(recordsperpage * (page - 1))
                .Take(recordsperpage)
                .ToList();

            List<Department> department = _context.Departments
                .Include(x => x.DepartmentCluster)
                .Where(x => x.IsActive.Equals(true))
                .ToList();

            Department? deptSel = await _context.Departments
                .SingleOrDefaultAsync(x => x.Id.Equals(deptId));

            string[] Month = ["JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER"];

            ReleasedViewModel model = new ReleasedViewModel();
            model.PaginationModel = new PaginationModel("Index", "Inventory", "", recordtotal, recordsperpage, page);
            model.Months = Month.ToList();
            model.releasedItems = released;
            model.items = items;
            model.departments = department;
            model.DeptId = deptId;
            model.searchtxt = searchTxt;
            model.YearFrom = yearFrom;
            model.YearTo = yearTo;
            if(years.Count() > 0)
            {
                model.year = years.Min();   
                model.year1Text = years.Min().ToString();
                model.year2Text = years.Max().ToString();
            }
            model.perPage = entries.ToString();
            model.toReceiveCount = CountToReceive.ToString();
            model.receivedCount = CountReceived.ToString();
            model.pullOutCount = CountPullout.ToString();
            model.TotalCount = CountTotal.ToString();
            if (deptSel != null)
            {
                model.DeptTxt = deptSel.Name;
                model.deptText = deptSel.NormalizedName;
            }
            else
            {
                model.deptText = "";
            }
            return View(model);
        }
    }
}

Views/Released/Index.cshtml
@using Microsoft.EntityFrameworkCore
@using IIMSv1.Data
@using IIMSv1.Models
@using IIMSv1.Models.ViewModel
@using IIMSv1.Models.Shared
@using Microsoft.AspNetCore.Identity
@model ReleasedViewModel
@{
    ViewBag.title = "Released";
    ViewBag.breadcrumbs = "<div class=\"breadcrumb-item active\">"
                        + ViewBag.title
                        + "</div>";
    List<_ItemReleasedModel> items = Model.items;
    List<Released> relItems = Model.releasedItems;
    List<string> Months = Model.Months;
}
<div class="row">
    <div class="col-lg-12">
        <div class="card border-bottom border-right border-left">
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-3 pt-xs-1 pt-sm-1 pt-t-md-1">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" id="txtsearch" name="search" value="@Model.searchtxt" style="height: 30px; font-size: 12px;" title="Search" />
                            <div class="input-group-text" title="Search">
                                <i class="ri-lg ri-search-line" style="font-size: 10px;"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-6 col-xl-5 pt-xs-1 pt-sm-1 pt-t-md-1">
                        <form asp-action="Index" asp-controller="PrintReleased" method="post" target="_blank">
                            <input class="form-select" name="searchtxt" value="@Model.searchtxt" type="hidden" />
                            <input class="form-select" name="department" value="@Model.DeptId" type="hidden" />
                            <input class="form-select" name="year1" value="@Model.YearFrom" type="hidden" />
                            <input class="form-select" name="year2" value="@Model.YearTo" type="hidden" />
                            <button class="btn btn-label btn-secondary btn-sm waves-effect waves-light" type="button" data-bs-toggle="modal" data-bs-target="#modal-filter">
                                <i class="ri-lg ri-filter-line label-icon align-middle fs-16 me-2"></i>
                                Filter
                            </button>
                            <button type="submit" class="btn btn-label btn-secondary btn-sm waves-effect waves-light">
                                <i class="ri-lg ri-printer-fill label-icon align-middle fs-16 me-2"></i>
                                Print
                            </button>
                        </form>
                    </div>
                    @await Html.PartialAsync("~/Views/Shared/_Entries.cshtml")
                </div>
                <div class="row mt-2">
                    <div class="col-lg-12">
                        @if (Model.searchtxt != "")
                        {
                            <div class="badge bg-primary-subtle text-primary badge-border w-auto" style="padding: .30rem .7rem; font-size: 12px;">
                                Showing results for <strong>"@Model.searchtxt"</strong>
                            </div>
                        }
                        @if (Model.deptText != "")
                        {
                            <div class="badge bg-primary-subtle text-primary badge-border w-auto" style="padding: .30rem .7rem; font-size: 12px;">
                                Department: <strong>"@Model.deptText"</strong>
                            </div>
                        }

                        @if (Model.YearFrom != "" || Model.YearTo != "")
                        {
                            <div class="badge bg-primary-subtle text-primary badge-border w-auto" style="padding: .30rem .7rem; font-size: 12px;">
                                Year: From <strong>"@Model.YearFrom"</strong> To <b>"@Model.YearTo"</b>
                            </div>
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="itemTbl">
                                <thead>
                                    <tr>
                                        <th rowspan="2" scope="col" class="text-center align-content-center" style="padding: 5px;">
                                            No.
                                        </th>
                                        <th rowspan="2" class="text-center align-content-center" style="padding: 5px;">
                                            ITEM
                                        </th>
                                        <th colspan="12" class="text-center align-content-center" style="padding: 5px;">MONTHS</th>
                                    </tr>
                                    <tr>
                                        @foreach (var m in Months)
                                        {
                                            <th class="text-center align-content-center" style="padding: 5px;">
                                                @m.Substring(0, 3)
                                            </th>
                                        }
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (items.Count > 0)
                                    {
                                        @foreach (var item in items)
                                        {
                                            <tr>
                                                <td scope="row" class="text-center align-content-center" width="3%" style="padding: 5px;">@item.num</td>
                                                <td class="font-weight-bold align-content-center" width="25%" style="padding: 5px;">@item.Name</td>
                                                @foreach (var m in Months)
                                                {
                                                    <td class="text-center align-content-center" style="padding: 5px;" width="6%">
                                                        @if (relItems.Count() > 0)
                                                        {
                                                            List<Released> rels = relItems
                                                            .Where(x => x.DateReleased.ToString("MMMM").ToUpper().Equals(m) && x.ItemId.Equals(item.Id))
                                                            .ToList();
                                                            if (rels.Count() > 0)
                                                            {
                                                                int Count = rels.Sum(x => x.ReleaseQuantity);
                                                                <span>@Count.ToString()</span>
                                                            }

                                                        }
                                                    </td>
                                                }
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        @if (items.Count() > 0)
                        {
                            @await Html.PartialAsync("~/Views/Shared/_Pagination.cshtml", Model.PaginationModel)
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section modals {
    @await Html.PartialAsync("~/Views/Released/Modal/_Filter.cshtml")
}
@section scripts {
    @await Html.PartialAsync("~/Views/Released/Shared/_scripts.cshtml")
}