Models/ViewModel/RecordsViewModel.cs
using IIMSv1.Models.Shared;

namespace IIMSv1.Models.ViewModel
{
    public class RecordsViewModel
    {

        public List<_RecordInputModel> record { get; set; } = new List<_RecordInputModel>();
        public List<string> year { get; set; } = new List<string>();
        public string yeartxt { get; set; } = string.Empty;
        public string relnum {  get; set; } = string.Empty;
        public string depttxt {  get; set; } = string.Empty;
        public string dateReleased { get; set; } = string.Empty;
        public string relnumtext { get; set; } = string.Empty;

    }
}

Controllers/PrintRecordsController.cs
using IIMSv1.Data;
using IIMSv1.Models;
using IIMSv1.Models.Shared;
using IIMSv1.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IIMSv1.Controllers
{
    public class PrintRecordsController : Controller
    {
        private readonly InventoryDbContext _context;
        private readonly UserManager<AccountUser> _userManager;
        private readonly SignInManager<AccountUser> _signInManager;

        public PrintRecordsController(InventoryDbContext context, UserManager<AccountUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<AccountUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        //Print Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> Index(string relnum = "", bool toReceive = false, bool received = false, bool pullout = false)
        {
            List<Released> releases = _context.Released
                .Include(x => x.item)
                .Include(x => x.Department)
                .Where(x => x.ReleaseNumber.Equals(relnum) && x.Department.IsActive.Equals(true))
                .ToList();

            if(releases.Count() == 0)
            {
                return NotFound();
            }

            string department = "";
            string dateOnly = "";
            int TotalQuantity = 0;
            int index = 1;
            List<_RecordInputModel> record = new List<_RecordInputModel>();
            foreach (var release in releases)
            {
                bool isDepartment = department.Any(x => x.Equals(release.Department.NormalizedName));
                if (!isDepartment)
                {
                    department = release.Department.NormalizedName;
                }

                bool isDate = dateOnly.Any(x => x.Equals(release.DateReleased));
                if (!isDate)
                {
                    dateOnly = release.DateReleased.ToShortDateString();
                }

                List<ReleaseHistory> history = _context.ReleaseHistory
                    .Where(x => x.ReleaseId == release.Id)
                    .ToList();
                string date = "";
                foreach (var h in history)
                {
                    bool isToReceive = h.Action.Equals("TO RECEIVE") && release.Received == false && release.Pullout == false;
                    if (isToReceive)
                    {
                        date = h.Date.ToShortDateString();
                    }
                    bool isReceived = h.Action.Equals("RECEIVED") && release.Received == true && release.Pullout == false;
                    if (isReceived)
                    {
                        date = h.Date.ToShortDateString();
                    }
                    bool isPullOut = h.Action.Equals("PULLOUT") && release.Received == false && release.Pullout == true;
                    if (isPullOut)
                    {
                        date = h.Date.ToShortDateString();
                    }
                }

                _RecordInputModel InRecord = new _RecordInputModel()
                {
                    num = index++,
                    Id = release.Id,
                    Item = release.item.ItemName,
                    Quantity = release.ReleaseQuantity,
                    Date = date,
                    IsReceived = release.Received,
                    IsPullout = release.Pullout,

                };
                TotalQuantity += release.ReleaseQuantity;
                record.Add(InRecord);

            }
            List<_RecordInputModel> ToReceiveRecords = new List<_RecordInputModel>();
            List<_RecordInputModel> ReceivedRecords = new List<_RecordInputModel>();
            List<_RecordInputModel> PullOutRecords = new List<_RecordInputModel>();
            foreach (var rec in record)
            {
                bool IsToReceive = rec.IsReceived.Equals(false) && rec.IsPullout.Equals(false);

                if (IsToReceive)
                {
                    ToReceiveRecords.Add(rec);
                }
            }
            foreach (var rec in record)
            {
                bool IsPullout = rec.IsReceived.Equals(false) && rec.IsPullout.Equals(true);

                if (IsPullout)
                {
                    PullOutRecords.Add(rec);
                }
            }
            foreach (var rec in record)
            {
                bool IsReceived = rec.IsReceived.Equals(true) && rec.IsPullout.Equals(false);

                if (IsReceived)
                {
                    ReceivedRecords.Add(rec);
                }
            }
            if (toReceive == true)
            {
               
            }
            else if (pullout == true)
            {
                
            }
            else if (received == true)
            {
               
            }
            

            PrintRecordsViewModel model = new PrintRecordsViewModel();
            model.record = record;
            model.relnumtext = relnum.ToString();
            if (toReceive == true)
            {
                model.ToReceiveRecords = ToReceiveRecords.OrderBy(x => x.Item).ToList();
            }
            else if (pullout == true)
            {
                model.PullOutRecords = PullOutRecords.OrderBy(x => x.Item).ToList();
            }
            else if (received == true)
            {
                model.ReceivedRecords = ReceivedRecords.OrderBy(x => x.Item).ToList();
            }
            else
            {
                model.ReceivedRecords = ReceivedRecords.OrderBy(x => x.Item).ToList();
                model.PullOutRecords = PullOutRecords.OrderBy(x => x.Item).ToList();
                model.ToReceiveRecords = ToReceiveRecords.OrderBy(x => x.Item).ToList();
            }
            model.dateReleased = dateOnly;
            model.depttxt = department;
            model.totalQuantity = TotalQuantity;

            return View(model);
        }
    }
}

Controllers/RecordsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IIMSv1.Data;
using IIMSv1.Models;
using IIMSv1.Models.Shared;
using IIMSv1.Models.ViewModel;

namespace IIMSv1.Controllers
{
    public class RecordsController : Controller
    {
        private readonly InventoryDbContext _context;
        private readonly UserManager<AccountUser> _userManager;
        private readonly SignInManager<AccountUser> _signInManager;

        public RecordsController(InventoryDbContext context, UserManager<AccountUser> userManager, RoleManager<IdentityRole> roleManager, SignInManager<AccountUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        //Search Realase Number 
        [HttpPost]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> _SearchRelNum(int relnum, string year)
        {
            return RedirectToAction("Index", "Records", new { relnum = relnum, year = year});
        }
        //Index
        [HttpGet]
        [Authorize(Roles = "Inventory Administrator")]
        public async Task<IActionResult> Index(int relnum = 0, string year = "")
        {
            AccountUser? user = await _userManager.GetUserAsync(User);

            AccountUser? currUser = await _context.AccountCredentials
                .Include(x => x.Employee)
               .ThenInclude(x => x.department)
                .SingleOrDefaultAsync(x => x.Id.Equals(user.Id));

            string relnumTxt = "RLSD" + "-" + year + "-" + relnum.ToString("000000");

            List<Released> releases = _context.Released
                .Include(x => x.Department)
                .Include(x => x.item)
                .ThenInclude(x => x.itemType)
                .OrderBy(x => x.item.itemType.itemType)
                .Where(x => x.ReleaseNumber.Equals(relnumTxt) && x.Department.IsActive.Equals(true))
                .ToList();

            string department = "";
            string dateOnly = "";
            int index = 1;

            List<_RecordInputModel> record = new List<_RecordInputModel>();
            foreach (var release in releases)
            {
                bool isDepartment = department.Any(x => x.Equals(release.Department.NormalizedName));
                if (!isDepartment)
                {
                    department = release.Department.NormalizedName;
                }

                bool isDate = dateOnly.Any(x => x.Equals(release.DateReleased));
                if (!isDate)
                {
                    dateOnly = release.DateReleased.ToShortDateString();
                }

                List<ReleaseHistory> history =  _context.ReleaseHistory
                    .Where(x => x.ReleaseId == release.Id)
                    .ToList();
                string date = "";
                foreach(var h in history)
                {
                        bool isToReceive = h.Action.Equals("TO RECEIVE") && release.Received == false && release.Pullout == false;
                        if (isToReceive)
                        {
                            date = h.Date.ToShortDateString();
                        }
                        bool isReceived = h.Action.Equals("RECEIVED") && release.Received == true && release.Pullout == false;
                        if (isReceived)
                        {
                            date = h.Date.ToShortDateString();
                        }
                        bool isPullOut = h.Action.Equals("PULLOUT") && release.Received == false && release.Pullout == true;
                        if (isPullOut)
                        {
                            date = h.Date.ToShortDateString();
                        }
                }
                _RecordInputModel InRecord = new _RecordInputModel()
                {
                    num = index++,
                    Id = release.Id,
                    Item = release.item.ItemName,
                    Quantity = release.ReleaseQuantity,
                    Date = date,
                    IsReceived = release.Received,
                    IsPullout = release.Pullout,

                };
                record.Add(InRecord);
            }

            List<Released> released = _context.Released
               .Include(x => x.Department)
               .Include(x => x.item)
               .ThenInclude(x => x.itemType)
               .OrderBy(x => x.item.itemType.itemType)
               .ToList();

            List<string> listYear = new List<string>();
            foreach (var release in released)
            {
                string[] splitYear = release.ReleaseNumber.Split('-');
                bool isYear = listYear.Any(x => x.Equals(splitYear[1]));
                if (!isYear)
                {
                    listYear.Add(splitYear[1]);
                }
            }
            RecordsViewModel model = new RecordsViewModel();
            model.record = record;
            model.year = listYear;
            model.yeartxt = year;
            model.relnumtext = relnumTxt;
            model.relnum = relnum.ToString("000000");
            model.dateReleased = dateOnly;
            model.depttxt = department;

            ViewBag.alert = TempData["alert"];
            return View(model);
        }
    }
}

Views/Records/Index.cshtml
@using Microsoft.EntityFrameworkCore
@using IIMSv1.Data
@using IIMSv1.Models
@using IIMSv1.Models.ViewModel
@using IIMSv1.Models.Shared
@using Microsoft.AspNetCore.Identity
@model RecordsViewModel
@{
    ViewBag.title = "Records";
    ViewBag.breadcrumbs = "<div class=\"breadcrumb-item active\">"
                        + ViewBag.title
                        + "</div>";
    List<_RecordInputModel> record = Model.record;
}
<div class="row">
    <div class="col-lg-12">
        <div class="card border-bottom border-right border-left">
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-3">
                        <div class="row">
                            <form asp-action="_SearchRelNum" asp-controller="Records" name="relNumForm">
                                <div class="col-lg-12 pb-3">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <label>Record Number: <span class="text-danger">*</span></label>
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="hstack gap-1">
                                            <input class="form-control text-center" type="text" value="RLSD" disabled />
                                            <span>-</span>
                                            <select class="form-select" name="year" id="yearRelNum" required>
                                                <option value="">Year</option>
                                                @foreach (var y in Model.year)
                                                {
                                                    <option value="@y">@y</option>
                                                }
                                            </select>
                                            <span>-</span>
                                            <input type="text" maxlength="6" class="form-control form-select-icon w-100" placeholder="Number" id="relnumTxt" name="relnum" value="@(Model.relnum != "000000" ? Model.relnum: "")" required />
                                        </div>
                                        
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <button class="btn btn-secondary w-100 mb-2" type="submit">Submit</button>
                                            <a href="@Url.Action("Index", "Records")" class="btn btn-light w-100">Reset</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="col-lg-12">
                                <div class="row">
                                    <div class="hstack">
                                        <table class="table table-bordered table-striped" id="ReleaseInfoTbl">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        <form asp-action="Index" asp-controller="PrintRecords" target="_blank">
                                                            <input class="form-select" type="hidden" name="relnum" value="@(record.Count > 0 ? Model.relnumtext : "")" />
                                                            <div class="hstack gap-2">
                                                                <span><strong>INFORMATION</strong></span>
                                                                <button type="submit" class="btn btn-secondary btn-sm ms-auto" data-bs-toggle="tooltip" data-bs-placement="top" title="print" @(record.Count > 0 ? "" : "disabled")>
                                                                    <i class="ri-lg ri-printer-fill"></i>
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><b>Record No.:</b></td>
                                                </tr>
                                                <tr>
                                                    <td class="pl-4">
                                                        @if (record.Count() > 0)
                                                        {
                                                            @Model.relnumtext
                                                        }
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td><b>Department:</b></td>
                                                </tr>
                                                <tr>
                                                    <td class="pl-4">@Model.depttxt</td>
                                                </tr>
                                                <tr>
                                                    <td><b>Date:</b></td>
                                                </tr>
                                                <tr>
                                                    <td class="pl-4">@Model.dateReleased</td>
                                                </tr>
                                                <tr>
                                                    <td><b>Total Item:</b></td>
                                                </tr>
                                                <tr>
                                                    <td class="pl-4">
                                                        @if (record.Count() > 0)
                                                        {
                                                            @record.Count()
                                                        }
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-9">
                        <div class="row">
                            <div class="col-lg-12">
                                @if (record.Count() == 0 && Model.relnumtext != "" && Model.yeartxt != "")
                                {
                                    <ul class="list-group mt-3">

                                        <li class="list-group-item">* No Records Found *</li>
                                    </ul>
                                }
                                else if (Model.relnumtext == "" && Model.yeartxt == ""){
                                    <ul class="list-group mt-3">
                                        <li class="list-group-item">* Please enter record number to see release records *</li>
                                    </ul>
                                }
                                
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                @if (record.Count() > 0)
                                {
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped" id="releasesRecord">
                                            <thead>
                                                <tr>
                                                    <th class="text-center align-content-center">NO.</th>
                                                    <th class="align-content-center">ITEM</th>
                                                    <th class="text-center align-content-center">QUANTITY</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var rel in record)
                                                {
                                                    <tr>
                                                        <td class="text-center align-content-center">@rel.num</td>
                                                        <td class="align-content-center">@rel.Item</td>
                                                        <td class="text-center align-content-center">@rel.Quantity</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                } 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section modals{

}
@section scripts {
    @await Html.PartialAsync("~/Views/Records/Shared/_scripts.cshtml")
}